src/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [ 
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('post/', include('posts.urls', namespace='post')),
    path('', include('user_registration.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/posts/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import PostDetailView, PostListAndCreateView, PostUpdateView, PostDeleteView

app_name = 'post'
urlpatterns = [
    # path('', home, name='home'),
    path('<int:pk>/', login_required(PostDetailView.as_view()), name='detail'),
    path('', login_required(PostListAndCreateView.as_view()), name='list'),
    path('<int:pk>/edit/', login_required(PostUpdateView.as_view()), name='update'),
    path('<int:pk>/delete/', login_required(PostDeleteView.as_view()), name='delete'),
]

src/templates/base/base_css.html
{% load static %}
<!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">-->
<!--<link rel="stylesheet" href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css">-->

<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/registration.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap-social.css' %}">
<link rel="stylesheet" href="{% static 'css/cropper.min.css' %}">
<link rel="stylesheet" href="{% static 'css/material-components-web.min.css' %}">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">


<style type="text/css">
    @media print {
        html,
        body {
            display: none;
        }
    }
</style>

src/templates/base/base_js.html
{% load static %}
<!--<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>-->
<!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>-->
<!--<script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js" type="text/javascript"></script>-->
<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>-->

<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/registration.js' %}"></script>
<script src="{% static 'js/cropper.min.js' %}"></script>
<script src="{% static 'js/material-components-web.min.js' %}"></script>

src/templates/base/base_registration.html
{% extends "base.html" %}

{% block head_title %}{% endblock %}

{% block body %}
<div class="row justify-content-center">
    <div class="col-lg-6 col-sm-12 col-md-9">
        <div style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19)">
            <div class="card">
                <div class="card-body">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

src/templates/base/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand mb-0 h1" href="{% url 'post:list' %}">{{sitename}}</a>
        <button aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
            class="navbar-toggler" data-target="#navbarSupportedContent" data-toggle="collapse" type="button">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'post:list' %}">Posts<span class="sr-only">(current)</span></a>
                </li>

            </ul>
            <form class="form-inline my-2 my-lg-0">
                {% if request.user.is_authenticated %}

                <ul class="navbar-nav mr-auto" id="dropdown">
                    <li class="dropdown">
                        <a aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#"
                            id="navbarDropdown" role="button">
                            <div>
                                {% if request.user.profile.image %}
                                <img alt="{{ request.user.get_full_name }}" class="border rounded-circle border-white"
                                    src="{{ request.user.profile.image.url }}" style="width:25px;" />
                                {% elif request.user.socialaccount_set.all.0.get_avatar_url %}
                                <img alt="{{ request.user.get_full_name }}" class="border rounded-circle border-white"
                                    src="{{ request.user.socialaccount_set.all.0.get_avatar_url }}"
                                    style="width:25px;" />
                                <!--0 indicates the site used to sign up first-->
                                {% else %}
                                <img alt="{{ request.user.get_full_name }}" class="border rounded-circle border-white"
                                    src="{% static 'images/profile.png' %}" style="width:25px;" />
                                {% endif %}
                            </div>
                        </a>
                        <ul aria-labelledby="navbarDropdown" class="dropdown-menu dropdown-menu-right">
                            <li><a class="dropdown-item" href="{% url 'user-profile' slug=request.user.username %}">My
                                    Profile</a></li>
                            <li>
                                <div class="dropdown-divider"></div>
                            </li>
                            <li><a class="dropdown-item" href="{% url 'settings' %}">Settings</a></li>
                            {% if user.is_superuser %}
                            <li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin Panel</a></li>
                            {% endif %}
                            <li>
                                <div class="dropdown-divider"></div>
                            </li>
                            <li><a class="dropdown-item" href="{% url 'account_logout' %}">Sign out</a></li>
                        </ul>
                    </li>
                </ul>

                {%else%}
                <a class="btn btn-outline-light mr-2" href="{% url 'account_login' %}">Sign in</a>
                <a class="btn btn-primary" href="{% url 'account_signup' %}">Sign up</a>
                {%endif%}
            </form>
        </div>
    </div>
</nav>
<script>

</script>