src/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [ 
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('post/', include('posts.urls', namespace='post')),
    path('', include('user_registration.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/posts/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import PostDetailView, PostListAndCreateView, PostUpdateView, PostDeleteView

app_name = 'post'
urlpatterns = [
    # path('', home, name='home'),
    path('<int:pk>/', login_required(PostDetailView.as_view()), name='detail'),
    path('', login_required(PostListAndCreateView.as_view()), name='list'),
    path('<int:pk>/edit/', login_required(PostUpdateView.as_view()), name='update'),
    path('<int:pk>/delete/', login_required(PostDeleteView.as_view()), name='delete'),
]

src/user_registration/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from .views import settings, UserDetailView, \
    UserDetailsUpdateView, UserProfileDetailsUpdateView, UserDeleteView
from allauth.account.views import EmailView as allauth_AccountEmail

urlpatterns = [
    path('accounts/email/', allauth_AccountEmail.as_view(), name='account_email'),
    path('accounts/', include('allauth.urls')),
    path('settings/', login_required(settings), name='settings'),
    path('settings/<slug>/update/', login_required(UserDetailsUpdateView.as_view()), name='upd-user'),
    path('settings/<slug>/delete/', login_required(UserDeleteView.as_view()), name='del-user'),
    path('settings/id/<int:pk>/update/', login_required(UserProfileDetailsUpdateView.as_view()), name='upd-profile'),
    path('profile/<slug>/', login_required(UserDetailView.as_view()), name='user-profile'),
]

src/user_registration/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse_lazy


# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='profile')
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True, null=True)
    birth_date = models.DateField(null=True, blank=True)
    image = models.ImageField(upload_to="profile_pic", null=True, blank=True)

    ##abc=...   User.abc.all()
    def get_absolute_url(self):
        return reverse_lazy("user-profile", kwargs={"slug": self.user.username})

    def __str__(self):
        return str(int(self.pk))

    class Meta:
        verbose_name = 'profile'
        verbose_name_plural = 'profiles'


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.get_or_create(user=instance)


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

src/user_registration/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm
from allauth.account.forms import SignupForm
from django import forms
from PIL import Image
from django.core.files import File
from .models import Profile


# UserForm,AddEmailForm


class CustomSignupForm(SignupForm):
    def __init__(self, *args, **kwargs):
        password1_help_text = '<ul>' \
                              '<li>Your password can\'t be too similar to your other personal information.</li>' \
                              '<li>Your password must contain at least 8 characters.</li>' \
                              '<li>Your password can\'t be a commonly used password.</li>' \
                              '<li>Your password can\'t be entirely numeric.</li>' \
                              '</ul>'
        super(CustomSignupForm, self).__init__(*args, **kwargs)
        self.fields['first_name'] = forms.CharField(max_length=30, required=True, label='First name',
                                                    widget=forms.TextInput(attrs={'placeholder': 'First name'}))
        self.fields['last_name'] = forms.CharField(max_length=30, required=True, label='Last name',
                                                   widget=forms.TextInput(attrs={'placeholder': 'Last name'}))
        self.fields['email'] = forms.EmailField(max_length=254, required=True,
                                                help_text='Required. Enter a valid email address.',
                                                label='E-mail', widget=forms.TextInput(attrs={'placeholder': 'E-mail'}))
        self.fields['username'] = forms.CharField(required=True,
                                                  help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
                                                  label='Username',
                                                  widget=forms.TextInput(attrs={'placeholder': 'Username'}))
        self.fields['password1'] = forms.CharField(required=True, help_text=password1_help_text, label='Password',
                                                   widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
        self.fields['password2'] = forms.CharField(required=True,
                                                   help_text='Enter the same password as before, for verification.',
                                                   label='Confirm Password',
                                                   widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
        self.fields['location'] = forms.CharField(max_length=30, required=False, label='Location',
                                                  widget=forms.TextInput(attrs={'placeholder': 'Location'}))
        self.fields['image'] = forms.ImageField(required=False)

        self.fields['x'] = forms.FloatField(required=False, widget=forms.HiddenInput())
        self.fields['y'] = forms.FloatField(required=False, widget=forms.HiddenInput())
        self.fields['width'] = forms.FloatField(required=False, widget=forms.HiddenInput())
        self.fields['height'] = forms.FloatField(required=False, widget=forms.HiddenInput())

    def save(self, request):
        user = super(CustomSignupForm, self).save(request)
        # Add your own processing here.
        # You must return the original result.
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        user.username = self.cleaned_data['username']
        user.set_password(self.cleaned_data['password1'])
        user.profile.location = self.cleaned_data['location']
        user.profile.image = self.cleaned_data['image']
        user.save()
        if user.profile.image:
            print('image present')
            x = self.cleaned_data.get('x')
            y = self.cleaned_data.get('y')
            w = self.cleaned_data.get('width')
            h = self.cleaned_data.get('height')
            print(x, y, w, h)
            images = Image.open(user.profile.image)
            cropped_image = images.crop((x, y, w + x, h + y))
            resized_image = cropped_image.resize((600, 600), Image.ANTIALIAS)
            resized_image.save(user.profile.image.path)
        return user

    field_order = ['first_name', 'last_name', 'email', 'username', 'password1', 'password2', 'location', 'image', 'x',
                   'y', 'width', 'height', ]


class UpdateUserForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30, required=False, label='First name',
                                 widget=forms.TextInput(attrs={'placeholder': 'First name'}))
    last_name = forms.CharField(max_length=30, required=False, label='Last name',
                                widget=forms.TextInput(attrs={'placeholder': 'Last name'}))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', ]


class UpdateProfileForm(forms.ModelForm):
    x = forms.FloatField(required=False, widget=forms.HiddenInput())
    y = forms.FloatField(required=False, widget=forms.HiddenInput())
    width = forms.FloatField(required=False, widget=forms.HiddenInput())
    height = forms.FloatField(required=False, widget=forms.HiddenInput())
    location = forms.CharField(max_length=30, required=False, label='Location',
                               widget=forms.TextInput(attrs={'placeholder': 'Location'}))
    image = forms.ImageField(required=False)

    class Meta:
        model = Profile
        fields = ['location', 'image', ]

    def save(self):
        user = super(UpdateProfileForm, self).save()
        user.location = self.cleaned_data.get('location')
        print("locations is", user.location)
        if not user.location:
            user.location = ""
        user.image = self.cleaned_data.get('image')
        print(user.image)
        user.save()
        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')
        if x or y or w or h:
            print('image present')
            image = Image.open(user.image)
            cropped_image = image.crop((x, y, w + x, h + y))
            resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
            resized_image.save(user.image.path)

        return user

src/user_registration/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import DetailView, UpdateView, DeleteView
from django.contrib.auth import get_user_model
from django.views import View
from .models import Profile
from django.urls import reverse_lazy
from django.forms.utils import ErrorList
from django import forms
from django.core.exceptions import PermissionDenied
from .forms import UpdateProfileForm, UpdateUserForm
from django import http
from posts.models import Post

User = get_user_model()

class UserDetailsUpdateView(UpdateView):
    template_name = "user/user_update.html"
    form_class = UpdateUserForm
    model = User
    slug_field = 'username'

    def get_context_data(self, *args, **kwargs):
        context = super(UserDetailsUpdateView,
                        self).get_context_data(*args, **kwargs)
        if context['user'] != self.request.user:
            raise PermissionDenied
        return context

    def get_success_url(self, *args, **kwargs):
        return reverse_lazy("upd-user", kwargs={'slug': self.request.user.username})


class UserProfileDetailsUpdateView(UpdateView):
    template_name = "user/user_profile_update.html"
    form_class = UpdateProfileForm
    model = Profile

    def get_context_data(self, *args, **kwargs):
        context = super(UserProfileDetailsUpdateView,
                        self).get_context_data(*args, **kwargs)
        print(context)
        if str(context['profile']) != str(int(self.request.user.pk)):
            raise PermissionDenied
        return context

    def get_success_url(self, *args, **kwargs):
        # context['profile']
        return reverse_lazy("upd-profile", kwargs={'pk': self.request.user.profile.user.id})


class UserDeleteView(DeleteView):
    model = User
    template_name = "user/user_delete_view.html"
    slug_field = 'username'
    success_url = reverse_lazy("account_login")

    def delete(self, request, *args, **kwargs):
        print("Users for delete are ", self.kwargs['slug'], self.request.user)
        if str(self.kwargs['slug']) == str(self.request.user.username):
            u = User.objects.get(username=self.request.user.username)
            u.delete()
            return redirect("account_login")
        else:
            # raise PermissionDenied
            return http.HttpResponseForbidden("Cannot delete other's account")


class UserDetailView(DetailView):
    queryset = User.objects.all()
    template_name = "user/user_profile.html"
    slug_field = 'username'

    def get_context_data(self, *args, **kwargs):
        context = super(UserDetailView, self).get_context_data(*args, **kwargs)
        context["object_list"] = Post.objects.filter(user=self.request.user)
        print(context)
        return context


@login_required(login_url='account_login')
def settings(request):
    return HttpResponseRedirect(reverse("upd-user", kwargs={'slug': request.user.username}))

src/user_registration/templates/user/user_delete_view.html
{% extends "settings.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block head_title %}{% trans "Update Profile" %}{% endblock %}


{% block content %}
<form class="form" method="POST">
    {% csrf_token %}
    <h2>Delete Account?</h2>
    <button class="btn btn-primary mr-2" id="delete" type="submit">Confirm Delete</button>
</form>

{%endblock%}

src/user_registration/templates/user/user_profile.html
{%extends 'base.html'%}
{% load static %}

{%block head_title%}
Profile
{%endblock head_title%}


{%block body%}

<div class="container">
    <div style="align-items: center;justify-content: center;text-align: center;">

        <div style="display: flex;align-items: center;justify-content: center;text-align: center;">
            {% if user.profile.image %}
            <img alt="{{ user.get_full_name }}" class="border rounded-circle border-white"
                id="following-image-{{user.username}}" src="{{ user.profile.image.url }}"
                style="width:75px;float: left;" />
            {% elif user.socialaccount_set.all.0.get_avatar_url %}
            <img alt="{{ user.get_full_name }}" class="border rounded-circle border-white"
                id="following-image-{{user.username}}" src="{{ user.socialaccount_set.all.0.get_avatar_url }}"
                style="width:75px;float: left;" />
            {% else %}
            <img alt="{{ user.get_full_name }}" class="border rounded-circle border-white"
                id="following-image-{{user.username}}" src="{% static 'images/profile.png' %}"
                style="width:75px;float: left;" />
            {% endif %}
            <h3><b>{{object.username}}</b></h3>
        </div>
        <br>



        <br><br>
        <h4>Posts</h4>
    </div>

    <div class="row">
        {% for object in object_list %}
        <div class="col-sm-12 col-lg-4" style="margin-bottom: 20px;">
            <div class="card h-100">
                <div class='card-body'>
                    <h5 class='card-title'>
                        <a href="{% url 'user-profile' slug=object.user.username %}" style='text-decoration:none;'>
                            {% if object.user.profile.image %}
                            <img alt="{{ object.user.get_full_name }}" class="border rounded-circle border-white"
                                src="{{ object.user.profile.image.url }}" style="width:25px;float: left;" />
                            {% elif object.user.socialaccount_set.all.0.get_avatar_url %}
                            <img alt="{{ object.user.get_full_name }}" class="border rounded-circle border-white"
                                src="{{ object.user.socialaccount_set.all.0.get_avatar_url }}"
                                style="width:25px;float: left;" />
                            <!--0 indicates the site used to sign up first-->
                            {% else %}
                            <img alt="{{ object.user.get_full_name }}" class="border rounded-circle border-white"
                                src="{% static 'images/profile.png' %}" style="width:25px;float: left;" />
                            {% endif %}
                            {{ object.user }}
                        </a>
                        {% if request.user.username == object.user.username %}
                        <span style='float: right;'>
                            <a data-toggle='dropdown'><img src="{% static 'images/more-24.png' %}"></a>
                            <div class='dropdown-menu dropdown-menu-right'>
                                <small><a class='dropdown-item post-upd'
                                        href="{% url 'post:update' pk=object.id %}">Update</a></small>
                                <small><a class='dropdown-item post-del'
                                        href="{% url 'post:delete' pk=object.id %}">Delete</a></small>
                            </div>
                        </span>
                        {% endif %}
                    </h5>
                    <small class='card-subtitle mb-2 text-muted'>
                        <a href="{% url 'post:detail' pk=object.id %}"
                            style='color:black;text-decoration:none;'>{{ object.updated_on }}</a>
                    </small>
                    <p class='card-text'>{{ object.content }}</p>
                    <img src="{{ object.image.url }}" style="width: 100%;height: 450px;object-fit: cover;" />
                </div>
            </div>
        </div>

        {% endfor %}
    </div>
    <br>
</div>

{%endblock%}

{% block javascript %}
<script>
    $(document).ready(function () {
        loadPostData("post-container")
    });
</script>
{% endblock %}

src/user_registration/templates/user/user_profile_update.html
{% extends "settings.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block head_title %}{% trans "Update Profile" %}{% endblock %}


{% block content %}
<form class="form" enctype='multipart/form-data' id="userprofileUpd" method="POST">
  {% csrf_token %}
  {{ form.location|as_crispy_field }}

  {{ form.x }}
  {{ form.y }}
  {{ form.width }}
  {{ form.height }}
  {% if request.user.profile.image %}
  <img alt="{{ request.user.get_full_name }}" class="border rounded-circle border-white"
    src="{{ request.user.profile.image.url }}" style="width:150px;" />
  {% elif request.user.socialaccount_set.all.0.get_avatar_url %}
  <img alt="{{ request.user.get_full_name }}" class="border rounded-circle border-white"
    src="{{ request.user.socialaccount_set.all.0.get_avatar_url }}" style="width:150px;" />
  <!--0 indicates the site used to sign up first-->
  {% else %}
  <img alt="{{ request.user.get_full_name }}" class="border rounded-circle border-white"
    src="{% static 'images/profile.png' %}" style="width:150px;" />
  {% endif %}
  <br>
  <div class="input-group">
    <div class="custom-file">
      {% comment %} <input accept="image/*" class="custom-file-input clearablefileinput" id="id_image" name="image"
        onchange="readCreateURL(this);" type="file">
      <label class="btn btn-primary" for="id_image" id="id_image_label">Browse</label> {% endcomment %}
      <label class="btn btn-outline-primary" for="id_image" id="id_image_label"> Browse <input accept="image/*"
          class="custom-file-input clearablefileinput" hidden id="id_image" name="image" type="file">
      </label>

    </div>
  </div>
  <br>
  <input class="btn btn-primary mr-2" type="submit" value="Update Profile">
</form>
{%endblock%}

{%block nocontainerbody%}
<div class="modal fade" id="modalCrop">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Crop the photo</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>

      </div>
      <div class="modal-body">
        <img src="" id="image" style="max-width: 100%;">
      </div>
      <div class="modal-footer">
        <div class="btn-group pull-left" role="group">
          <button type="button" class="btn btn-default js-zoom-in">
            <span class="glyphicon glyphicon-zoom-in"></span>
          </button>
          <button type="button" class="btn btn-default js-zoom-out">
            <span class="glyphicon glyphicon-zoom-out"></span>
          </button>
        </div>
        <button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
        <button type="button" class="btn btn-primary js-crop-and-upload">Crop and upload</button>
      </div>
    </div>
  </div>
</div>
{%endblock nocontainerbody%}


{% block javascript %}
<script>
  $(function () {

    /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
    $("#id_image").change(function () {
      if (this.files && this.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
          $("#image").attr("src", e.target.result);
          console.log(e.target.result)
          $("#modalCrop").modal("show");
        }
        reader.readAsDataURL(this.files[0]);
      }
    });

    /* SCRIPTS TO HANDLE THE CROPPER BOX */
    var $image = $("#image");
    var cropBoxData;
    var canvasData;
    $("#modalCrop").on("shown.bs.modal", function () {
      $image.cropper({
        viewMode: 1,
        aspectRatio: 1 / 1,
        minCropBoxWidth: 200,
        minCropBoxHeight: 200,
        ready: function () {
          $image.cropper("setCanvasData", canvasData);
          $image.cropper("setCropBoxData", cropBoxData);
        }
      });
    }).on("hidden.bs.modal", function () {
      cropBoxData = $image.cropper("getCropBoxData");
      canvasData = $image.cropper("getCanvasData");
      $image.cropper("destroy");
    });

    $(".js-zoom-in").click(function () {
      $image.cropper("zoom", 0.1);
    });

    $(".js-zoom-out").click(function () {
      $image.cropper("zoom", -0.1);
    });

    /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
    $(".js-crop-and-upload").click(function () {
      var cropData = $image.cropper("getData");
      $("#id_x").val(cropData["x"]);
      $("#id_y").val(cropData["y"]);
      $("#id_height").val(cropData["height"]);
      $("#id_width").val(cropData["width"]);
      $('#modalCrop').modal('hide');
      console.log(cropData["x"], cropData["y"], cropData["height"], cropData["width"])
      $("#userprofileUpd").submit();
    });
  });
</script>
{% endblock %}

src/user_registration/templates/user/user_update.html
{% extends "settings.html" %}

{% load crispy_forms_tags %}
{% load i18n %}

{% block head_title %}{% trans "Update Profile" %}{% endblock %}


{% block content %}
<form class="form" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary mr-2" type="submit" value="Update User">
</form>
{%endblock%}

src/user_registration/templates/user/users_modal.html
{% load static %}
<!-- Modal -->
<div aria-hidden="true" aria-labelledby="FollowingModalLongTitle" class="modal fade" id="FollowingModalLong"
    role="dialog" tabindex="-1">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="FollowingModalLongTitle">Following</h5>
                <button aria-label="Close" class="close" data-dismiss="modal" type="button">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <ul class="list-group" id='following-list'>
                    {% for user in followingusers %}
                    <li class="list-group-item" id='following-list-{{user.username}}'>
                        <h5>
                            <a href="/profile/{{user.username}}" style='text-decoration:none;'>
                                {% if user.profile.image %}
                                <img alt="{{ user.get_full_name }}" class="border rounded-circle border-white"
                                    id="following-image-{{user.username}}" src="{{ user.profile.image.url }}"
                                    style="width:26px;float: left;" />
                                {% elif user.socialaccount_set.all.0.get_avatar_url %}
                                <img alt="{{ user.get_full_name }}" class="border rounded-circle border-white"
                                    id="following-image-{{user.username}}"
                                    src="{{ user.socialaccount_set.all.0.get_avatar_url }}"
                                    style="width:26px;float: left;" />
                                {% else %}
                                <img alt="{{ user.get_full_name }}" class="border rounded-circle border-white"
                                    id="following-image-{{user.username}}" src="{% static 'images/profile.png' %}"
                                    style="width:26px;float: left;" />
                                {% endif %}
                                &nbsp;&nbsp;{{user.username}}</a>
                            <a class="btn btn-outline-primary user-following" data-id='{{user.username}}'
                                href="{% url 'user-follow' slug=user.username %}" id='following-{{user.username}}'
                                style="width:90px;float:right;">Following</a>

                        </h5>
                    </li>
                    {% empty %}
                    <h6 id='notfollow1'>Not following any users!</h6>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="FollowersModalLong" tabindex="-1" role="dialog" aria-labelledby="FollowersModalLongTitle"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="FollowersModalLongTitle">Followers</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <ul class="list-group" id='follower-list'>
                    {% for user in followersusers %}
                    <li class="list-group-item" id='follower-list-{{user.user.username}}'
                        data-id='{{user.user.username}}'>
                        <h5>
                            <a href="/profile/{{user.user.username}}" style='text-decoration:none;'>
                                {% if user.user.profile.image %}
                                <img src="{{ user.user.profile.image.url }}" alt="{{ user.user.get_full_name }}"
                                    style="width:26px;float: left;" class="border rounded-circle border-white" />
                                {% elif user.user.socialaccount_set.all.0.get_avatar_url %}
                                <img src="{{ user.user.socialaccount_set.all.0.get_avatar_url }}"
                                    alt="{{ user.user.get_full_name }}" style="width:26px;float: left;"
                                    class="border rounded-circle border-white" />
                                <!--0 indicates the site used to sign up first-->
                                {% else %}
                                <img src="{% static 'images/profile.png' %}" alt="{{ user.user.get_full_name }}"
                                    style="width:26px;float: left;" class="border rounded-circle border-white" />
                                {% endif %}
                                &nbsp;&nbsp;{{user.user.username}}</a>
                            <div style="width:110px;float:right;">
                                {% if user.user.username in followusers %}
                                <a href="{% url 'user-follow' slug=user.user.username %}"
                                    class="btn btn-outline-primary user-follower" data-id='{{user.user.username}}'
                                    id='follower-{{user.user.username}}' style="width:90px;">Following</a>
                                {% else %}
                                <a href="{% url 'user-follow' slug=user.user.username %}"
                                    class="btn btn-primary user-follower" data-id='{{user.user.username}}'
                                    id='follower-{{user.user.username}}' style="width:90px;">Follow</a>
                                {% endif %}
                                {% ifequal request.user.username object.username %}
                                <a href="{% url 'user-follow-remove' slug=user.user.username %}"
                                    class="user-followremove" data-id='{{user.user.username}}'
                                    id='follower-{{user.user.username}}'
                                    style="width:10px;float:right;text-decoration:none;">&times;</a>
                                {% endifequal %}
                            </div>
                        </h5>
                    </li>
                    {% empty %}
                    <h6 id='notfollow2'>Not followed by any users!</h6>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>